<?php

use Illuminate\Database\Seeder;

class ActionEventsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('action_events')->delete();
        
        \DB::table('action_events')->insert(array (
            0 => 
            array (
                'id' => 5,
                'batch_id' => '92a24e87-1baf-43b2-a561-1b931097339b',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 16,
                'target_type' => 'App\\Competence',
                'target_id' => 16,
                'model_type' => 'App\\Competence',
                'model_id' => 16,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 09:26:38',
                'updated_at' => '2021-02-02 09:26:38',
                'original' => NULL,
                'changes' => '{"description":"qwdqwd","updated_at":"2021-02-02T09:26:38.000000Z","created_at":"2021-02-02T09:26:38.000000Z","id":16}',
            ),
            1 => 
            array (
                'id' => 6,
                'batch_id' => '92a24e87-31bd-4587-a01f-06e6e8dd1955',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 9,
                'target_type' => 'App\\Level',
                'target_id' => 9,
                'model_type' => 'App\\Level',
                'model_id' => 9,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 09:26:38',
                'updated_at' => '2021-02-02 09:26:38',
                'original' => NULL,
                'changes' => '{"title":"qwdqwdqwd","updated_at":"2021-02-02T09:26:38.000000Z","created_at":"2021-02-02T09:26:38.000000Z","id":9}',
            ),
            2 => 
            array (
                'id' => 7,
                'batch_id' => '92a24e98-459a-47da-8613-556a8bd8bc2a',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 16,
                'target_type' => 'App\\Competence',
                'target_id' => 16,
                'model_type' => 'App\\Competence',
                'model_id' => 16,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 09:26:49',
                'updated_at' => '2021-02-02 09:26:49',
                'original' => '[]',
                'changes' => '[]',
            ),
            3 => 
            array (
                'id' => 8,
                'batch_id' => '92a24e98-6fcf-41f9-bcd2-b40b72fbccce',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 17,
                'target_type' => 'App\\Competence',
                'target_id' => 17,
                'model_type' => 'App\\Competence',
                'model_id' => 17,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 09:26:49',
                'updated_at' => '2021-02-02 09:26:49',
                'original' => NULL,
                'changes' => '{"description":"qwdqwdqw","updated_at":"2021-02-02T09:26:49.000000Z","created_at":"2021-02-02T09:26:49.000000Z","id":17}',
            ),
            4 => 
            array (
                'id' => 9,
                'batch_id' => '92a24e98-7c8d-47dc-a296-a524b1f27685',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 9,
                'target_type' => 'App\\Level',
                'target_id' => 9,
                'model_type' => 'App\\Level',
                'model_id' => 9,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 09:26:49',
                'updated_at' => '2021-02-02 09:26:49',
                'original' => '[]',
                'changes' => '[]',
            ),
            5 => 
            array (
                'id' => 10,
                'batch_id' => '92a24ea3-f9b7-4b13-a79d-64287ad540d6',
                'user_id' => 4,
                'name' => 'Delete',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 9,
                'target_type' => 'App\\Level',
                'target_id' => 9,
                'model_type' => 'App\\Level',
                'model_id' => 9,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 09:26:57',
                'updated_at' => '2021-02-02 09:26:57',
                'original' => NULL,
                'changes' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'batch_id' => '92a28aa4-63c6-42c4-95a1-f24e2c3ddd52',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:14:43',
                'updated_at' => '2021-02-02 12:14:43',
                'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<\\/div>"}',
                'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Voorbeeld van Variabelen in Javascript.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Voorbeeld van Variabelen in Javascript.<\\/figcaption><\\/a><\\/figure><\\/div>"}',
            ),
            7 => 
            array (
                'id' => 12,
                'batch_id' => '92a28afe-8531-4f6f-b12e-86ca87aef6d0',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:15:42',
                'updated_at' => '2021-02-02 12:15:42',
                'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Voorbeeld van Variabelen in Javascript.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Voorbeeld van Variabelen in Javascript.<\\/figcaption><\\/a><\\/figure><\\/div>"}',
                'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><\\/div>"}',
            ),
            8 => 
            array (
                'id' => 13,
                'batch_id' => '92a28b9b-b2cc-40e1-a014-111b3021bc3c',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:17:25',
                'updated_at' => '2021-02-02 12:17:25',
                'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><\\/div>"}',
                'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><a href=\\"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y\\">Dit is een youtube video<\\/a><br><br><\\/div>"}',
            ),
            9 => 
            array (
                'id' => 14,
                'batch_id' => '92a28c78-4b6a-455f-9fca-7f9c2e94c7b6',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:19:50',
                'updated_at' => '2021-02-02 12:19:50',
                'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><a href=\\"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y\\">Dit is een youtube video<\\/a><br><br><\\/div>"}',
            'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>switch&nbsp;<\\/li><\\/ul><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><a href=\\"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y\\">Dit is een youtube video<\\/a><br><br><\\/div>"}',
            ),
            10 => 
            array (
                'id' => 15,
                'batch_id' => '92a28d93-84a9-4a72-acd0-e9fe58432be5',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:22:56',
                'updated_at' => '2021-02-02 12:22:56',
            'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>switch&nbsp;<\\/li><\\/ul><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><a href=\\"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y\\">Dit is een youtube video<\\/a><br><br><\\/div>"}',
            'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<\\/strong><br><a href=\\"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y\\">Dit is een youtube video<\\/a><br><br><\\/div>"}',
            ),
            11 => 
            array (
                'id' => 16,
                'batch_id' => '92a290aa-725a-4774-a2de-88c6f444fb4a',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 1,
                'target_type' => 'App\\Material',
                'target_id' => 1,
                'model_type' => 'App\\Material',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:31:34',
                'updated_at' => '2021-02-02 12:31:34',
                'original' => NULL,
                'changes' => '{"title":"Youtube Video over Variabelen","link":"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y","subject_id":2,"updated_at":"2021-02-02T12:31:34.000000Z","created_at":"2021-02-02T12:31:34.000000Z","id":1}',
            ),
            12 => 
            array (
                'id' => 17,
                'batch_id' => '92a290aa-82d4-4d28-a4c2-5fb4f71e70b7',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 2,
                'target_type' => 'App\\Subject',
                'target_id' => 2,
                'model_type' => 'App\\Subject',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:31:34',
                'updated_at' => '2021-02-02 12:31:34',
                'original' => '{"description":"Je gaat in deze les leren op welke verschillende manieren loops gebruikt kunnen worden."}',
                'changes' => '{"description":"<div>Je gaat in deze les leren op welke verschillende manieren loops gebruikt kunnen worden.<\\/div>"}',
            ),
            13 => 
            array (
                'id' => 18,
                'batch_id' => '92a291ee-6f8e-439a-86a3-67bffa57b8f4',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:35:06',
                'updated_at' => '2021-02-02 12:35:06',
                'original' => NULL,
                'changes' => '{"title":"Variabelen in Javascript","link":"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y","subject_id":1,"updated_at":"2021-02-02T12:35:06.000000Z","created_at":"2021-02-02T12:35:06.000000Z","id":2}',
            ),
            14 => 
            array (
                'id' => 19,
                'batch_id' => '92a291ee-8107-444c-9f9c-0c06d0d1701c',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:35:06',
                'updated_at' => '2021-02-02 12:35:06',
                'original' => '[]',
                'changes' => '[]',
            ),
            15 => 
            array (
                'id' => 20,
                'batch_id' => '92a293d6-0408-44ad-97c7-cb1c8b53047f',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:40:26',
                'updated_at' => '2021-02-02 12:40:26',
                'original' => '{"title":"Variabelen in Javascript","link":"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y"}',
                'changes' => '{"title":"W3Schools Javascript - Home","link":"https:\\/\\/www.w3schools.com\\/js\\/default.asp"}',
            ),
            16 => 
            array (
                'id' => 21,
                'batch_id' => '92a293d6-3589-47a6-b65a-011132b59dbc',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 3,
                'target_type' => 'App\\Material',
                'target_id' => 3,
                'model_type' => 'App\\Material',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:40:26',
                'updated_at' => '2021-02-02 12:40:26',
                'original' => NULL,
                'changes' => '{"title":"W3Schools Javascript - Introduction","link":"https:\\/\\/www.w3schools.com\\/js\\/js_intro.asp","subject_id":1,"updated_at":"2021-02-02T12:40:26.000000Z","created_at":"2021-02-02T12:40:26.000000Z","id":3}',
            ),
            17 => 
            array (
                'id' => 22,
                'batch_id' => '92a293d6-5d27-44e8-ae0b-1c6904259e6e',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 4,
                'target_type' => 'App\\Material',
                'target_id' => 4,
                'model_type' => 'App\\Material',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:40:26',
                'updated_at' => '2021-02-02 12:40:26',
                'original' => NULL,
                'changes' => '{"title":"W3Schools Javascript - Where To","link":"https:\\/\\/www.w3schools.com\\/js\\/js_whereto.asp","subject_id":1,"updated_at":"2021-02-02T12:40:26.000000Z","created_at":"2021-02-02T12:40:26.000000Z","id":4}',
            ),
            18 => 
            array (
                'id' => 23,
                'batch_id' => '92a293d6-65f1-47f3-a5d2-ceeda8d3774e',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 12:40:26',
                'updated_at' => '2021-02-02 12:40:26',
                'original' => '[]',
                'changes' => '[]',
            ),
            19 => 
            array (
                'id' => 24,
                'batch_id' => '92a29db4-e04c-4960-af76-1f25c1034f95',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:08:02',
                'updated_at' => '2021-02-02 13:08:02',
                'original' => '[]',
                'changes' => '[]',
            ),
            20 => 
            array (
                'id' => 25,
                'batch_id' => '92a29db5-12ee-4b46-aeb9-cd3ec7cfa7fb',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 3,
                'target_type' => 'App\\Material',
                'target_id' => 3,
                'model_type' => 'App\\Material',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:08:02',
                'updated_at' => '2021-02-02 13:08:02',
                'original' => '[]',
                'changes' => '[]',
            ),
            21 => 
            array (
                'id' => 26,
                'batch_id' => '92a29db5-3965-4cf8-9c6b-e85ed9a0f970',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 4,
                'target_type' => 'App\\Material',
                'target_id' => 4,
                'model_type' => 'App\\Material',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:08:02',
                'updated_at' => '2021-02-02 13:08:02',
                'original' => '[]',
                'changes' => '[]',
            ),
            22 => 
            array (
                'id' => 27,
                'batch_id' => '92a29db5-4204-4025-a02c-025247ac9f11',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:08:02',
                'updated_at' => '2021-02-02 13:08:02',
            'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<\\/strong><br><a href=\\"https:\\/\\/www.youtube.com\\/watch?v=WJ3-F02-F_Y\\">Dit is een youtube video<\\/a><br><br><\\/div>"}',
            'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<\\/strong><br>&lt;<strong>iframe<\\/strong> width=\\"420\\" height=\\"315\\" src=\\"https:\\/\\/www.youtube.com\\/embed\\/eI4an8aSsgw\\"&gt;<br>&lt;\\/<strong>iframe<\\/strong>&gt;<\\/div>"}',
            ),
            23 => 
            array (
                'id' => 28,
                'batch_id' => '92a29e87-111b-4178-8755-53b42647d7e8',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:10:20',
                'updated_at' => '2021-02-02 13:10:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            24 => 
            array (
                'id' => 29,
                'batch_id' => '92a29e87-471b-4693-a247-843cef3191e5',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 3,
                'target_type' => 'App\\Material',
                'target_id' => 3,
                'model_type' => 'App\\Material',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:10:20',
                'updated_at' => '2021-02-02 13:10:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            25 => 
            array (
                'id' => 30,
                'batch_id' => '92a29e87-70a8-441e-adbf-8781c25fa59d',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 4,
                'target_type' => 'App\\Material',
                'target_id' => 4,
                'model_type' => 'App\\Material',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:10:20',
                'updated_at' => '2021-02-02 13:10:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            26 => 
            array (
                'id' => 31,
                'batch_id' => '92a29e87-7a07-41f4-a759-437f2ce9a4d7',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:10:20',
                'updated_at' => '2021-02-02 13:10:20',
            'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<\\/strong><br>&lt;<strong>iframe<\\/strong> width=\\"420\\" height=\\"315\\" src=\\"https:\\/\\/www.youtube.com\\/embed\\/eI4an8aSsgw\\"&gt;<br>&lt;\\/<strong>iframe<\\/strong>&gt;<\\/div>"}',
            'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<\\/strong><\\/div><pre>    &lt;iframe width=\\"420\\" height=\\"315\\" src=\\"https:\\/\\/www.youtube.com\\/embed\\/eI4an8aSsgw\\"&gt;&lt;\\/iframe&gt;<\\/pre>"}',
            ),
            27 => 
            array (
                'id' => 32,
                'batch_id' => '92a29f45-d606-49c1-846f-40e5e6240869',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:25',
                'updated_at' => '2021-02-02 13:12:25',
                'original' => '[]',
                'changes' => '[]',
            ),
            28 => 
            array (
                'id' => 33,
                'batch_id' => '92a29f46-0a5d-4f21-9a6a-9d9564f6cf9b',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 3,
                'target_type' => 'App\\Material',
                'target_id' => 3,
                'model_type' => 'App\\Material',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:25',
                'updated_at' => '2021-02-02 13:12:25',
                'original' => '[]',
                'changes' => '[]',
            ),
            29 => 
            array (
                'id' => 34,
                'batch_id' => '92a29f46-2f96-49e5-b5f3-ce92854d29ef',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 4,
                'target_type' => 'App\\Material',
                'target_id' => 4,
                'model_type' => 'App\\Material',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:25',
                'updated_at' => '2021-02-02 13:12:25',
                'original' => '[]',
                'changes' => '[]',
            ),
            30 => 
            array (
                'id' => 35,
                'batch_id' => '92a29f46-3908-4452-8214-da37206827ec',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:25',
                'updated_at' => '2021-02-02 13:12:25',
            'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<\\/strong><\\/div><pre>    &lt;iframe width=\\"420\\" height=\\"315\\" src=\\"https:\\/\\/www.youtube.com\\/embed\\/eI4an8aSsgw\\"&gt;&lt;\\/iframe&gt;<\\/pre>"}',
            'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<br><\\/strong>Hier is een Iframe hard-coded toegevoegd omdat met de huidige opbouw er geen ruimte was voor video\'s. Dit is puur ter illustratie als voorbeeld toegevoegd. Er zou in de toekomst een soort les builder gemaakt kunnen worden waar alle vormgeving al in is gedaan en alleen content moet kunnen worden toegevoegd.<\\/div>"}',
            ),
            31 => 
            array (
                'id' => 36,
                'batch_id' => '92a29f67-95ef-465f-839a-16a747598bbe',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:47',
                'updated_at' => '2021-02-02 13:12:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            32 => 
            array (
                'id' => 37,
                'batch_id' => '92a29f67-c36f-4737-9210-95a0217dc8f0',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 3,
                'target_type' => 'App\\Material',
                'target_id' => 3,
                'model_type' => 'App\\Material',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:47',
                'updated_at' => '2021-02-02 13:12:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            33 => 
            array (
                'id' => 38,
                'batch_id' => '92a29f67-ea89-4afd-83ec-93c8fb7ed32a',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 4,
                'target_type' => 'App\\Material',
                'target_id' => 4,
                'model_type' => 'App\\Material',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:47',
                'updated_at' => '2021-02-02 13:12:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            34 => 
            array (
                'id' => 39,
                'batch_id' => '92a29f67-f3f4-47f2-aed8-7627543cf986',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 13:12:47',
                'updated_at' => '2021-02-02 13:12:47',
            'original' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<br><\\/strong>Hier is een Iframe hard-coded toegevoegd omdat met de huidige opbouw er geen ruimte was voor video\'s. Dit is puur ter illustratie als voorbeeld toegevoegd. Er zou in de toekomst een soort les builder gemaakt kunnen worden waar alle vormgeving al in is gedaan en alleen content moet kunnen worden toegevoegd.<\\/div>"}',
            'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<br><br><strong>Bestudeer op w3schools.com (javascript tutorial):&nbsp;<\\/strong><\\/div><ul><li>Home&nbsp;<\\/li><li>Introduction<\\/li><li>Where to<\\/li><li>Output&nbsp;<\\/li><li>Syntax<\\/li><li>Statements<\\/li><li>Comments<\\/li><li>Variables<\\/li><li>Operators<\\/li><li>Arithmetic<\\/li><li>Assignment<\\/li><li>Data types<\\/li><li>Functions<\\/li><li>Conditions<\\/li><li>Switch<\\/li><\\/ul><div><br><strong>Hoe declareer je een variabele in Javascript?<br><\\/strong>Onderstaand zie je een voorbeeld van hoe je een variabele declareert in Javascript.<\\/div><div><br><figure data-trix-attachment=\\"{&quot;contentType&quot;:&quot;image\\/png&quot;,&quot;filename&quot;:&quot;image.png&quot;,&quot;filesize&quot;:5553,&quot;height&quot;:229,&quot;href&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;url&quot;:&quot;http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png&quot;,&quot;width&quot;:245}\\" data-trix-content-type=\\"image\\/png\\" data-trix-attributes=\\"{&quot;caption&quot;:&quot;Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.&quot;,&quot;presentation&quot;:&quot;gallery&quot;}\\" class=\\"attachment attachment--preview attachment--png\\"><a href=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\"><img src=\\"http:\\/\\/level-up.test\\/storage\\/y5IcMIDPVm3U4o7nD575mD9NN1t4VDAZqColsl6r.png\\" width=\\"245\\" height=\\"229\\"><figcaption class=\\"attachment__caption attachment__caption--edited\\">Bovenstaand een voorbeeld van hoe variabelen in Javascript worden gedefineerd.<\\/figcaption><\\/a><\\/figure><br><br><strong>Dit is een voorbeeld van een link met daarin een Youtube Video.<br><\\/strong>Hier is een Iframe hard-coded toegevoegd omdat met de huidige opbouw er geen ruimte was voor video\'s. Dit is puur ter illustratie als voorbeeld toegevoegd. Er zou in de toekomst een soort les builder gemaakt kunnen worden waar alle vormgeving al in is gedaan en alleen content moet kunnen worden toegevoegd.<br><br><\\/div>"}',
            ),
            35 => 
            array (
                'id' => 40,
                'batch_id' => '92a2b4b3-2eb7-4950-a5b3-0e75cbafbcb7',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 2,
                'target_type' => 'App\\Material',
                'target_id' => 2,
                'model_type' => 'App\\Material',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 14:12:20',
                'updated_at' => '2021-02-02 14:12:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            36 => 
            array (
                'id' => 41,
                'batch_id' => '92a2b4b3-603c-4250-ad0c-d19e862603fa',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 3,
                'target_type' => 'App\\Material',
                'target_id' => 3,
                'model_type' => 'App\\Material',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 14:12:20',
                'updated_at' => '2021-02-02 14:12:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            37 => 
            array (
                'id' => 42,
                'batch_id' => '92a2b4b3-89a2-4212-bcff-c60fb8806b87',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 4,
                'target_type' => 'App\\Material',
                'target_id' => 4,
                'model_type' => 'App\\Material',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 14:12:20',
                'updated_at' => '2021-02-02 14:12:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            38 => 
            array (
                'id' => 43,
                'batch_id' => '92a2b4b3-b124-43db-b71b-9774482616d1',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 5,
                'target_type' => 'App\\Material',
                'target_id' => 5,
                'model_type' => 'App\\Material',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 14:12:20',
                'updated_at' => '2021-02-02 14:12:20',
                'original' => NULL,
                'changes' => '{"title":"W3Schools Javascript - Syntax","link":"https:\\/\\/www.w3schools.com\\/js\\/js_syntax.asp","subject_id":1,"updated_at":"2021-02-02T14:12:20.000000Z","created_at":"2021-02-02T14:12:20.000000Z","id":5}',
            ),
            39 => 
            array (
                'id' => 44,
                'batch_id' => '92a2b4b3-bca1-40d7-b351-c909bb3a6d04',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 14:12:20',
                'updated_at' => '2021-02-02 14:12:20',
                'original' => '[]',
                'changes' => '[]',
            ),
            40 => 
            array (
                'id' => 45,
                'batch_id' => '92a2cf30-a0ea-45e0-978f-933626fb2f36',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Answer',
                'actionable_id' => 3,
                'target_type' => 'App\\Answer',
                'target_id' => 3,
                'model_type' => 'App\\Answer',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:26:24',
                'updated_at' => '2021-02-02 15:26:24',
                'original' => NULL,
            'changes' => '{"answer":"for (var i = 0; i < cars.length; i++) {   text += cars[i] + \\"<br>\\"; }","is_correct":true,"assignment_id":8,"updated_at":"2021-02-02T15:26:24.000000Z","created_at":"2021-02-02T15:26:24.000000Z","id":3}',
            ),
            41 => 
            array (
                'id' => 46,
                'batch_id' => '92a2cf30-b2f1-47fb-b57c-a3b1cbb1c31e',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Assignment',
                'actionable_id' => 8,
                'target_type' => 'App\\Assignment',
                'target_id' => 8,
                'model_type' => 'App\\Assignment',
                'model_id' => 8,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:26:24',
                'updated_at' => '2021-02-02 15:26:24',
                'original' => NULL,
                'changes' => '{"title":"Hoe werkt een loop in Javascript?","description":"Kijk heel goed naar bron 2","updated_at":"2021-02-02T15:26:24.000000Z","created_at":"2021-02-02T15:26:24.000000Z","id":8,"is_done":false}',
            ),
            42 => 
            array (
                'id' => 47,
                'batch_id' => '92a2cf30-ee44-47ea-8c7e-c21f1e8e0285',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Material',
                'actionable_id' => 1,
                'target_type' => 'App\\Material',
                'target_id' => 1,
                'model_type' => 'App\\Material',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:26:24',
                'updated_at' => '2021-02-02 15:26:24',
                'original' => '[]',
                'changes' => '[]',
            ),
            43 => 
            array (
                'id' => 48,
                'batch_id' => '92a2cf30-f82c-4e22-9b0d-a521fbc60bc0',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 2,
                'target_type' => 'App\\Subject',
                'target_id' => 2,
                'model_type' => 'App\\Subject',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:26:24',
                'updated_at' => '2021-02-02 15:26:24',
                'original' => '{"title":"Studieblok 2: Loops in Javascript"}',
                'changes' => '{"title":"Loops in Javascript"}',
            ),
            44 => 
            array (
                'id' => 49,
                'batch_id' => '92a2d056-e921-4cd9-ac38-e71571ad9d49',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Answer',
                'actionable_id' => 4,
                'target_type' => 'App\\Answer',
                'target_id' => 4,
                'model_type' => 'App\\Answer',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:29:37',
                'updated_at' => '2021-02-02 15:29:37',
                'original' => NULL,
            'changes' => '{"answer":"for(var i = 0; i < cars.length; i++) {   text += cars[i] + \\"<br>\\"; }","is_correct":true,"assignment_id":9,"updated_at":"2021-02-02T15:29:37.000000Z","created_at":"2021-02-02T15:29:37.000000Z","id":4}',
            ),
            45 => 
            array (
                'id' => 50,
                'batch_id' => '92a2d057-0d1e-409a-9bee-e68c5a951611',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Answer',
                'actionable_id' => 5,
                'target_type' => 'App\\Answer',
                'target_id' => 5,
                'model_type' => 'App\\Answer',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:29:37',
                'updated_at' => '2021-02-02 15:29:37',
                'original' => NULL,
            'changes' => '{"answer":"for($i = 0; $i < cars.length; $i++) {   console.log(cars[i].name); }","is_correct":false,"assignment_id":9,"updated_at":"2021-02-02T15:29:37.000000Z","created_at":"2021-02-02T15:29:37.000000Z","id":5}',
            ),
            46 => 
            array (
                'id' => 51,
                'batch_id' => '92a2d057-16d4-4ff2-bdf9-de0262d13031',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Assignment',
                'actionable_id' => 9,
                'target_type' => 'App\\Assignment',
                'target_id' => 9,
                'model_type' => 'App\\Assignment',
                'model_id' => 9,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:29:37',
                'updated_at' => '2021-02-02 15:29:37',
                'original' => NULL,
                'changes' => '{"title":"Wat is de correcte syntax voor een loop in Javascript?","description":"Tip! Kijk goed naar bron 2.","updated_at":"2021-02-02T15:29:37.000000Z","created_at":"2021-02-02T15:29:37.000000Z","id":9,"is_done":false}',
            ),
            47 => 
            array (
                'id' => 52,
                'batch_id' => '92a2d057-3107-4139-a1b2-895cd077d927',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 3,
                'target_type' => 'App\\Subject',
                'target_id' => 3,
                'model_type' => 'App\\Subject',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:29:37',
                'updated_at' => '2021-02-02 15:29:37',
                'original' => NULL,
                'changes' => '{"title":"Simpele Loops","description":"<div>Hier krijg je wat introductie over basic loops.<\\/div>","updated_at":"2021-02-02T15:29:36.000000Z","created_at":"2021-02-02T15:29:36.000000Z","id":3,"tags":[]}',
            ),
            48 => 
            array (
                'id' => 53,
                'batch_id' => '92a2d057-3f96-4cf6-b9c2-8527dfbb4c9d',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 2,
                'target_type' => 'App\\Lesson',
                'target_id' => 2,
                'model_type' => 'App\\Lesson',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-02 15:29:37',
                'updated_at' => '2021-02-02 15:29:37',
                'original' => '[]',
                'changes' => '[]',
            ),
        ));

        
    }
}