<?php

use Illuminate\Database\Seeder;

class ActionEventsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('action_events')->delete();
        
        \DB::table('action_events')->insert(array (
            0 => 
            array (
                'id' => 1,
                'batch_id' => '92a14821-08c4-4075-8368-5ca6fa4bbc35',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:12:55',
                'updated_at' => '2021-02-01 21:12:55',
                'original' => NULL,
                'changes' => '{"description":"qwf","updated_at":"2021-02-01T21:12:54.000000Z","created_at":"2021-02-01T21:12:54.000000Z","id":1}',
            ),
            1 => 
            array (
                'id' => 2,
                'batch_id' => '92a14821-2c4d-4498-aff4-5282346b8788',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:12:55',
                'updated_at' => '2021-02-01 21:12:55',
                'original' => NULL,
                'changes' => '{"title":"qwf","updated_at":"2021-02-01T21:12:54.000000Z","created_at":"2021-02-01T21:12:54.000000Z","id":4}',
            ),
            2 => 
            array (
                'id' => 3,
                'batch_id' => '92a14821-3118-44c4-9ab0-0a156e57aa51',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 4,
                'target_type' => 'App\\Course',
                'target_id' => 4,
                'model_type' => 'App\\Course',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:12:55',
                'updated_at' => '2021-02-01 21:12:55',
                'original' => NULL,
                'changes' => '{"title":"qwf","description":"qwfqwf","updated_at":"2021-02-01T21:12:54.000000Z","created_at":"2021-02-01T21:12:54.000000Z","id":4}',
            ),
            3 => 
            array (
                'id' => 4,
                'batch_id' => '92a1482e-0db6-4bac-b593-3268b7303dd3',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:13:03',
                'updated_at' => '2021-02-01 21:13:03',
                'original' => '[]',
                'changes' => '[]',
            ),
            4 => 
            array (
                'id' => 5,
                'batch_id' => '92a1482e-21cb-435e-975b-d1daff9c172e',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 2,
                'target_type' => 'App\\Competence',
                'target_id' => 2,
                'model_type' => 'App\\Competence',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:13:03',
                'updated_at' => '2021-02-01 21:13:03',
                'original' => NULL,
                'changes' => '{"description":"qwfqwf","updated_at":"2021-02-01T21:13:03.000000Z","created_at":"2021-02-01T21:13:03.000000Z","id":2}',
            ),
            5 => 
            array (
                'id' => 6,
                'batch_id' => '92a1482e-262c-4654-96b5-8ea1b0830791',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:13:03',
                'updated_at' => '2021-02-01 21:13:03',
                'original' => '[]',
                'changes' => '[]',
            ),
            6 => 
            array (
                'id' => 7,
                'batch_id' => '92a1482e-2bee-4c92-aa1c-b6fbb16f2fd3',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 4,
                'target_type' => 'App\\Course',
                'target_id' => 4,
                'model_type' => 'App\\Course',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:13:03',
                'updated_at' => '2021-02-01 21:13:03',
                'original' => '[]',
                'changes' => '[]',
            ),
            7 => 
            array (
                'id' => 26,
                'batch_id' => '92a1533b-5568-49ca-b53c-44fb5d3c298b',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 3,
                'target_type' => 'App\\Competence',
                'target_id' => 3,
                'model_type' => 'App\\Competence',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:43:57',
                'updated_at' => '2021-02-01 21:43:57',
                'original' => NULL,
                'changes' => '{"description":"qwdqwd","updated_at":"2021-02-01T21:43:57.000000Z","created_at":"2021-02-01T21:43:57.000000Z","id":3}',
            ),
            8 => 
            array (
                'id' => 27,
                'batch_id' => '92a15345-7153-43a2-a57c-f122f7722c4e',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:44:04',
                'updated_at' => '2021-02-01 21:44:04',
                'original' => NULL,
                'changes' => '{"competence_id":"3","level_id":"4"}',
            ),
            9 => 
            array (
                'id' => 28,
                'batch_id' => '92a15356-1bee-431f-886d-d7b1c1b82bb7',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Competence',
                'target_id' => 2,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:44:15',
                'updated_at' => '2021-02-01 21:44:15',
                'original' => NULL,
                'changes' => NULL,
            ),
            10 => 
            array (
                'id' => 29,
                'batch_id' => '92a15356-24b8-4545-822e-66b2ec5a9cf1',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:44:15',
                'updated_at' => '2021-02-01 21:44:15',
                'original' => '[]',
                'changes' => '[]',
            ),
            11 => 
            array (
                'id' => 30,
                'batch_id' => '92a15356-2e75-4e4e-8c15-5b4a6712d815',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 3,
                'target_type' => 'App\\Competence',
                'target_id' => 3,
                'model_type' => 'App\\Competence',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:44:15',
                'updated_at' => '2021-02-01 21:44:15',
                'original' => '[]',
                'changes' => '[]',
            ),
            12 => 
            array (
                'id' => 31,
                'batch_id' => '92a15356-338b-41ed-bf5d-1aea460a2f07',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:44:15',
                'updated_at' => '2021-02-01 21:44:15',
                'original' => '[]',
                'changes' => '[]',
            ),
            13 => 
            array (
                'id' => 32,
                'batch_id' => '92a15356-377b-4036-aee7-a7a861957fb4',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 4,
                'target_type' => 'App\\Course',
                'target_id' => 4,
                'model_type' => 'App\\Course',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:44:15',
                'updated_at' => '2021-02-01 21:44:15',
                'original' => '[]',
                'changes' => '[]',
            ),
            14 => 
            array (
                'id' => 42,
                'batch_id' => '92a153f4-83ab-4599-9861-beb04a9db357',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:45:59',
                'updated_at' => '2021-02-01 21:45:59',
                'original' => '[]',
                'changes' => '[]',
            ),
            15 => 
            array (
                'id' => 43,
                'batch_id' => '92a153f4-8fce-492c-baf7-0f89fa0fd037',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 3,
                'target_type' => 'App\\Competence',
                'target_id' => 3,
                'model_type' => 'App\\Competence',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:45:59',
                'updated_at' => '2021-02-01 21:45:59',
                'original' => '[]',
                'changes' => '[]',
            ),
            16 => 
            array (
                'id' => 44,
                'batch_id' => '92a153f4-939a-452b-b4a5-c7e6a2d445ef',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:45:59',
                'updated_at' => '2021-02-01 21:45:59',
                'original' => '[]',
                'changes' => '[]',
            ),
            17 => 
            array (
                'id' => 45,
                'batch_id' => '92a153f4-977b-4fb7-84ac-77d3e0d5074d',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 4,
                'target_type' => 'App\\Course',
                'target_id' => 4,
                'model_type' => 'App\\Course',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:45:59',
                'updated_at' => '2021-02-01 21:45:59',
                'original' => '[]',
                'changes' => '[]',
            ),
            18 => 
            array (
                'id' => 49,
                'batch_id' => '92a15427-764b-43e6-9da6-7b4c56109751',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:32',
                'updated_at' => '2021-02-01 21:46:32',
                'original' => '[]',
                'changes' => '[]',
            ),
            19 => 
            array (
                'id' => 50,
                'batch_id' => '92a15427-8291-4c92-8f7c-a45553d0d22e',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 3,
                'target_type' => 'App\\Competence',
                'target_id' => 3,
                'model_type' => 'App\\Competence',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:32',
                'updated_at' => '2021-02-01 21:46:32',
                'original' => '[]',
                'changes' => '[]',
            ),
            20 => 
            array (
                'id' => 51,
                'batch_id' => '92a15427-8d8d-4165-ba3c-274460dea485',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 4,
                'target_type' => 'App\\Competence',
                'target_id' => 4,
                'model_type' => 'App\\Competence',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:32',
                'updated_at' => '2021-02-01 21:46:32',
                'original' => NULL,
                'changes' => '{"description":"weqwe","updated_at":"2021-02-01T21:46:32.000000Z","created_at":"2021-02-01T21:46:32.000000Z","id":4}',
            ),
            21 => 
            array (
                'id' => 52,
                'batch_id' => '92a15427-9137-4d3c-8484-18eea8227cf4',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:32',
                'updated_at' => '2021-02-01 21:46:32',
                'original' => '[]',
                'changes' => '[]',
            ),
            22 => 
            array (
                'id' => 53,
                'batch_id' => '92a1543e-5076-42b0-ad34-3861bc5300ca',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:47',
                'updated_at' => '2021-02-01 21:46:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            23 => 
            array (
                'id' => 54,
                'batch_id' => '92a1543e-5be4-49bf-974b-aa8be006904f',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 3,
                'target_type' => 'App\\Competence',
                'target_id' => 3,
                'model_type' => 'App\\Competence',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:47',
                'updated_at' => '2021-02-01 21:46:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            24 => 
            array (
                'id' => 55,
                'batch_id' => '92a1543e-63e9-4502-b60f-ddc6fd1f9579',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 4,
                'target_type' => 'App\\Competence',
                'target_id' => 4,
                'model_type' => 'App\\Competence',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:47',
                'updated_at' => '2021-02-01 21:46:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            25 => 
            array (
                'id' => 56,
                'batch_id' => '92a1543e-6dbd-490a-aaac-898280065de3',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 5,
                'target_type' => 'App\\Competence',
                'target_id' => 5,
                'model_type' => 'App\\Competence',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:47',
                'updated_at' => '2021-02-01 21:46:47',
                'original' => NULL,
                'changes' => '{"description":"qwdqwdqwdqwd","updated_at":"2021-02-01T21:46:47.000000Z","created_at":"2021-02-01T21:46:47.000000Z","id":5}',
            ),
            26 => 
            array (
                'id' => 57,
                'batch_id' => '92a1543e-71bd-41c2-b007-054363cadf51',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:46:47',
                'updated_at' => '2021-02-01 21:46:47',
                'original' => '[]',
                'changes' => '[]',
            ),
            27 => 
            array (
                'id' => 58,
                'batch_id' => '92a154a0-e946-43dd-94e7-34cc12042cfb',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:47:52',
                'updated_at' => '2021-02-01 21:47:52',
                'original' => NULL,
                'changes' => NULL,
            ),
            28 => 
            array (
                'id' => 59,
                'batch_id' => '92a154a0-ef9d-4f13-802d-1db64045e692',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Competence',
                'target_id' => 3,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:47:52',
                'updated_at' => '2021-02-01 21:47:52',
                'original' => NULL,
                'changes' => NULL,
            ),
            29 => 
            array (
                'id' => 60,
                'batch_id' => '92a154a0-f310-4f06-a15b-2305f96439fb',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Competence',
                'target_id' => 4,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:47:52',
                'updated_at' => '2021-02-01 21:47:52',
                'original' => NULL,
                'changes' => NULL,
            ),
            30 => 
            array (
                'id' => 61,
                'batch_id' => '92a154a0-f93f-4228-a068-c45312a35fd6',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 5,
                'target_type' => 'App\\Competence',
                'target_id' => 5,
                'model_type' => 'App\\Competence',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:47:52',
                'updated_at' => '2021-02-01 21:47:52',
                'original' => '[]',
                'changes' => '[]',
            ),
            31 => 
            array (
                'id' => 62,
                'batch_id' => '92a154a0-fea5-4eb4-ad35-eeb8178840dc',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:47:52',
                'updated_at' => '2021-02-01 21:47:52',
                'original' => '[]',
                'changes' => '[]',
            ),
            32 => 
            array (
                'id' => 63,
                'batch_id' => '92a154a1-028e-44d2-8ae4-1b92a6e756b3',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 4,
                'target_type' => 'App\\Course',
                'target_id' => 4,
                'model_type' => 'App\\Course',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:47:52',
                'updated_at' => '2021-02-01 21:47:52',
                'original' => '[]',
                'changes' => '[]',
            ),
            33 => 
            array (
                'id' => 68,
                'batch_id' => '92a15529-4232-46ce-85f0-a5c6c477c05b',
                'user_id' => 4,
                'name' => 'Delete',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 4,
                'target_type' => 'App\\Course',
                'target_id' => 4,
                'model_type' => 'App\\Course',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:49:21',
                'updated_at' => '2021-02-01 21:49:21',
                'original' => NULL,
                'changes' => NULL,
            ),
            34 => 
            array (
                'id' => 69,
                'batch_id' => '92a15558-8d9e-408b-8527-a00e16485fb8',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 6,
                'target_type' => 'App\\Competence',
                'target_id' => 6,
                'model_type' => 'App\\Competence',
                'model_id' => 6,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:49:52',
                'updated_at' => '2021-02-01 21:49:52',
                'original' => NULL,
                'changes' => '{"description":"Voorstellen in het engels","updated_at":"2021-02-01T21:49:52.000000Z","created_at":"2021-02-01T21:49:52.000000Z","id":6}',
            ),
            35 => 
            array (
                'id' => 70,
                'batch_id' => '92a15558-964f-496d-87d6-67359474431c',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 5,
                'target_type' => 'App\\Level',
                'target_id' => 5,
                'model_type' => 'App\\Level',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:49:52',
                'updated_at' => '2021-02-01 21:49:52',
                'original' => NULL,
                'changes' => '{"title":"Level 1","updated_at":"2021-02-01T21:49:52.000000Z","created_at":"2021-02-01T21:49:52.000000Z","id":5}',
            ),
            36 => 
            array (
                'id' => 71,
                'batch_id' => '92a15558-9a7f-47c5-9642-78377ed1c5a4',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 3,
                'target_type' => 'App\\Course',
                'target_id' => 3,
                'model_type' => 'App\\Course',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:49:52',
                'updated_at' => '2021-02-01 21:49:52',
                'original' => '[]',
                'changes' => '[]',
            ),
            37 => 
            array (
                'id' => 72,
                'batch_id' => '92a15586-22e6-42ed-ae26-5ac86f26ff0e',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 7,
                'target_type' => 'App\\Competence',
                'target_id' => 7,
                'model_type' => 'App\\Competence',
                'model_id' => 7,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:50:22',
                'updated_at' => '2021-02-01 21:50:22',
                'original' => NULL,
            'changes' => '{"description":"Kan eenvoudige voorwaardelijke code (if\\/switch) en herhaalde code (for\\/while) toepassen bij het realiseren van een eenvoudige applicatie. B1-K2-W1","updated_at":"2021-02-01T21:50:22.000000Z","created_at":"2021-02-01T21:50:22.000000Z","id":7}',
            ),
            38 => 
            array (
                'id' => 73,
                'batch_id' => '92a15586-2aac-42fb-8f77-e8114aad8b61',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 2,
                'model_type' => 'App\\Level',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:50:22',
                'updated_at' => '2021-02-01 21:50:22',
                'original' => '[]',
                'changes' => '[]',
            ),
            39 => 
            array (
                'id' => 74,
                'batch_id' => '92a15586-335e-4f55-8f9f-d1113fde12f2',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:50:22',
                'updated_at' => '2021-02-01 21:50:22',
                'original' => '[]',
                'changes' => '[]',
            ),
            40 => 
            array (
                'id' => 75,
                'batch_id' => '92a15586-3706-498c-bfb5-237a043b448d',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 2,
                'target_type' => 'App\\Course',
                'target_id' => 2,
                'model_type' => 'App\\Course',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:50:22',
                'updated_at' => '2021-02-01 21:50:22',
                'original' => '[]',
                'changes' => '[]',
            ),
            41 => 
            array (
                'id' => 76,
                'batch_id' => '92a155db-8d10-4656-a273-caad745bccf0',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 7,
                'target_type' => 'App\\Competence',
                'target_id' => 7,
                'model_type' => 'App\\Competence',
                'model_id' => 7,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:18',
                'updated_at' => '2021-02-01 21:51:18',
                'original' => '[]',
                'changes' => '[]',
            ),
            42 => 
            array (
                'id' => 77,
                'batch_id' => '92a155db-9bc1-4e7a-b0d4-a7752946766b',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 8,
                'target_type' => 'App\\Competence',
                'target_id' => 8,
                'model_type' => 'App\\Competence',
                'model_id' => 8,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:18',
                'updated_at' => '2021-02-01 21:51:18',
                'original' => NULL,
                'changes' => '{"description":"Kan het verloop van een algoritme beschrijven, bijvoorbeeld aan de hand van een PSD. B1-K2-W3","updated_at":"2021-02-01T21:51:18.000000Z","created_at":"2021-02-01T21:51:18.000000Z","id":8}',
            ),
            43 => 
            array (
                'id' => 78,
                'batch_id' => '92a155db-9f74-449a-9a7a-0ddb2168d936',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 2,
                'model_type' => 'App\\Level',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:18',
                'updated_at' => '2021-02-01 21:51:18',
                'original' => '{"title":"Level 2"}',
                'changes' => '{"title":"Level 1"}',
            ),
            44 => 
            array (
                'id' => 79,
                'batch_id' => '92a155db-a93a-42cc-b9fe-e7999bf5d48d',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 1,
                'target_type' => 'App\\Competence',
                'target_id' => 1,
                'model_type' => 'App\\Competence',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:18',
                'updated_at' => '2021-02-01 21:51:18',
                'original' => '[]',
                'changes' => '[]',
            ),
            45 => 
            array (
                'id' => 80,
                'batch_id' => '92a155db-ad61-43c7-89df-83d8561b1240',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 2,
                'target_type' => 'App\\Course',
                'target_id' => 2,
                'model_type' => 'App\\Course',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:18',
                'updated_at' => '2021-02-01 21:51:18',
                'original' => '[]',
                'changes' => '[]',
            ),
            46 => 
            array (
                'id' => 81,
                'batch_id' => '92a15606-32c7-47bc-bf8b-9cfafe337fc3',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 9,
                'target_type' => 'App\\Competence',
                'target_id' => 9,
                'model_type' => 'App\\Competence',
                'model_id' => 9,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:46',
                'updated_at' => '2021-02-01 21:51:46',
                'original' => NULL,
                'changes' => '{"description":"qweqweqweqwe","updated_at":"2021-02-01T21:51:46.000000Z","created_at":"2021-02-01T21:51:46.000000Z","id":9}',
            ),
            47 => 
            array (
                'id' => 82,
                'batch_id' => '92a15606-3b4b-4e1d-a0db-d28c97f96190',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 6,
                'target_type' => 'App\\Level',
                'target_id' => 6,
                'model_type' => 'App\\Level',
                'model_id' => 6,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:46',
                'updated_at' => '2021-02-01 21:51:46',
                'original' => NULL,
                'changes' => '{"title":"wat is deez","updated_at":"2021-02-01T21:51:46.000000Z","created_at":"2021-02-01T21:51:46.000000Z","id":6}',
            ),
            48 => 
            array (
                'id' => 83,
                'batch_id' => '92a15606-3f12-438e-bce7-5b9636115dee',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 5,
                'target_type' => 'App\\Course',
                'target_id' => 5,
                'model_type' => 'App\\Course',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:51:46',
                'updated_at' => '2021-02-01 21:51:46',
                'original' => NULL,
                'changes' => '{"title":"nieuwe leerlijn","description":"yoo","updated_at":"2021-02-01T21:51:46.000000Z","created_at":"2021-02-01T21:51:46.000000Z","id":5}',
            ),
            49 => 
            array (
                'id' => 88,
                'batch_id' => '92a1564e-b732-4778-8ba2-5d6428ba541c',
                'user_id' => 4,
                'name' => 'Delete',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 5,
                'target_type' => 'App\\Course',
                'target_id' => 5,
                'model_type' => 'App\\Course',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:52:33',
                'updated_at' => '2021-02-01 21:52:33',
                'original' => NULL,
                'changes' => NULL,
            ),
            50 => 
            array (
                'id' => 89,
                'batch_id' => '92a156cb-f912-47a9-9eb6-1976d5633fc8',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 10,
                'target_type' => 'App\\Competence',
                'target_id' => 10,
                'model_type' => 'App\\Competence',
                'model_id' => 10,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:53:55',
                'updated_at' => '2021-02-01 21:53:55',
                'original' => NULL,
                'changes' => '{"description":"Kan webpagina\\u2019s maken met HTML5 en CSS3 waarbij inhoud en opmaak duidelijk gescheiden zijn.  B1-k2-w1","updated_at":"2021-02-01T21:53:55.000000Z","created_at":"2021-02-01T21:53:55.000000Z","id":10}',
            ),
            51 => 
            array (
                'id' => 90,
                'batch_id' => '92a156cc-077f-4cff-9a3e-44839bd2718e',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 11,
                'target_type' => 'App\\Competence',
                'target_id' => 11,
                'model_type' => 'App\\Competence',
                'model_id' => 11,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:53:56',
                'updated_at' => '2021-02-01 21:53:56',
                'original' => NULL,
                'changes' => '{"description":"Kan online documentatie toepassen om nog niet bekende onderdelen van HTML5 en CSS3 toe te passen.","updated_at":"2021-02-01T21:53:56.000000Z","created_at":"2021-02-01T21:53:56.000000Z","id":11}',
            ),
            52 => 
            array (
                'id' => 91,
                'batch_id' => '92a156cc-0b2f-449d-856c-773f58754166',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 1,
                'target_type' => 'App\\Level',
                'target_id' => 1,
                'model_type' => 'App\\Level',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:53:56',
                'updated_at' => '2021-02-01 21:53:56',
                'original' => '[]',
                'changes' => '[]',
            ),
            53 => 
            array (
                'id' => 92,
                'batch_id' => '92a156cc-1321-4648-afa2-ca1ea45ec5cb',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 2,
                'target_type' => 'App\\Competence',
                'target_id' => 2,
                'model_type' => 'App\\Competence',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:53:56',
                'updated_at' => '2021-02-01 21:53:56',
                'original' => '[]',
                'changes' => '[]',
            ),
            54 => 
            array (
                'id' => 93,
                'batch_id' => '92a156cc-16dc-4b2a-8689-51a54c0965e0',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 1,
                'target_type' => 'App\\Course',
                'target_id' => 1,
                'model_type' => 'App\\Course',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 21:53:56',
                'updated_at' => '2021-02-01 21:53:56',
                'original' => '[]',
                'changes' => '[]',
            ),
            55 => 
            array (
                'id' => 94,
                'batch_id' => '92a15aba-2f3b-4be7-9a7d-fb804470e152',
                'user_id' => 4,
                'name' => 'Delete',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 6,
                'target_type' => 'App\\Level',
                'target_id' => 6,
                'model_type' => 'App\\Level',
                'model_id' => 6,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:04:55',
                'updated_at' => '2021-02-01 22:04:55',
                'original' => NULL,
                'changes' => NULL,
            ),
            56 => 
            array (
                'id' => 95,
                'batch_id' => '92a15abe-d065-441b-9ae4-98a0cd9c385f',
                'user_id' => 4,
                'name' => 'Delete',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 4,
                'model_type' => 'App\\Level',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:04:58',
                'updated_at' => '2021-02-01 22:04:58',
                'original' => NULL,
                'changes' => NULL,
            ),
            57 => 
            array (
                'id' => 96,
                'batch_id' => '92a15af3-1d1b-4594-be3e-a4e8db5752bd',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 7,
                'target_type' => 'App\\Competence',
                'target_id' => 7,
                'model_type' => 'App\\Competence',
                'model_id' => 7,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:05:32',
                'updated_at' => '2021-02-01 22:05:32',
                'original' => '[]',
                'changes' => '[]',
            ),
            58 => 
            array (
                'id' => 97,
                'batch_id' => '92a15af3-2e14-4c77-86cd-21a2bb01eab8',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 8,
                'target_type' => 'App\\Competence',
                'target_id' => 8,
                'model_type' => 'App\\Competence',
                'model_id' => 8,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:05:32',
                'updated_at' => '2021-02-01 22:05:32',
                'original' => '[]',
                'changes' => '[]',
            ),
            59 => 
            array (
                'id' => 98,
                'batch_id' => '92a15af3-31fd-499c-bf3d-203243d3bb31',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 2,
                'model_type' => 'App\\Level',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:05:32',
                'updated_at' => '2021-02-01 22:05:32',
                'original' => '{"title":"Level 1"}',
                'changes' => '{"title":"Level 2"}',
            ),
            60 => 
            array (
                'id' => 99,
                'batch_id' => '92a15cda-b675-4c5a-8b6f-a1868a6f0849',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 1,
                'target_type' => 'App\\Lesson',
                'target_id' => 1,
                'model_type' => 'App\\Lesson',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:10:52',
                'updated_at' => '2021-02-01 22:10:52',
                'original' => '[]',
                'changes' => '[]',
            ),
            61 => 
            array (
                'id' => 100,
                'batch_id' => '92a15cda-c65c-4dd5-97b7-666ac6a18c51',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 2,
                'target_type' => 'App\\Lesson',
                'target_id' => 2,
                'model_type' => 'App\\Lesson',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:10:52',
                'updated_at' => '2021-02-01 22:10:52',
                'original' => NULL,
                'changes' => '{"title":"qwd","description":"qwdqwdq","updated_at":"2021-02-01T22:10:52.000000Z","created_at":"2021-02-01T22:10:52.000000Z","id":2}',
            ),
            62 => 
            array (
                'id' => 101,
                'batch_id' => '92a15cda-ca22-4c94-b9fc-f4e7b7841d7c',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 1,
                'target_type' => 'App\\Module',
                'target_id' => 1,
                'model_type' => 'App\\Module',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:10:52',
                'updated_at' => '2021-02-01 22:10:52',
                'original' => '[]',
                'changes' => '[]',
            ),
            63 => 
            array (
                'id' => 102,
                'batch_id' => '92a15d16-6e60-4cde-ad89-f41e0db5a901',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 1,
                'target_type' => 'App\\Lesson',
                'target_id' => 1,
                'model_type' => 'App\\Lesson',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:11:31',
                'updated_at' => '2021-02-01 22:11:31',
                'original' => '[]',
                'changes' => '[]',
            ),
            64 => 
            array (
                'id' => 103,
                'batch_id' => '92a15d16-7b88-4d43-924a-fadc7bc3cbbc',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 2,
                'target_type' => 'App\\Lesson',
                'target_id' => 2,
                'model_type' => 'App\\Lesson',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:11:31',
                'updated_at' => '2021-02-01 22:11:31',
                'original' => '{"title":"qwd","description":"qwdqwdq"}',
                'changes' => '{"title":"Studieblok 2: Loops in Javascript","description":"Je gaat in deze les leren op welke verschillende manieren loops gebruikt kunnen worden."}',
            ),
            65 => 
            array (
                'id' => 104,
                'batch_id' => '92a15d16-8176-455c-8e34-08d0bd8b2d00',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 1,
                'target_type' => 'App\\Module',
                'target_id' => 1,
                'model_type' => 'App\\Module',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:11:31',
                'updated_at' => '2021-02-01 22:11:31',
                'original' => '[]',
                'changes' => '[]',
            ),
            66 => 
            array (
                'id' => 142,
                'batch_id' => '92a16288-6f40-49c1-a024-edb1b3428c10',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Course',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 2,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:26:44',
                'updated_at' => '2021-02-01 22:26:44',
                'original' => NULL,
                'changes' => NULL,
            ),
            67 => 
            array (
                'id' => 146,
                'batch_id' => '92a162dc-12a1-49d4-84a3-d9aa20a53b86',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 12,
                'target_type' => 'App\\Competence',
                'target_id' => 12,
                'model_type' => 'App\\Competence',
                'model_id' => 12,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:27:39',
                'updated_at' => '2021-02-01 22:27:39',
                'original' => NULL,
                'changes' => '{"description":"Kan langere code opdelen in kleinere onderdelen door bijvoorbeeld functies\\/methoden te gebruiken. In de code worden herhaalde code-regels zo veel mogelijk voorkomen. B1-k2-w1 b1-k3-w1","updated_at":"2021-02-01T22:27:39.000000Z","created_at":"2021-02-01T22:27:39.000000Z","id":12}',
            ),
            68 => 
            array (
                'id' => 147,
                'batch_id' => '92a162dc-1ade-4ca9-ab9e-6a2cb7744998',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 7,
                'target_type' => 'App\\Level',
                'target_id' => 7,
                'model_type' => 'App\\Level',
                'model_id' => 7,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:27:39',
                'updated_at' => '2021-02-01 22:27:39',
                'original' => NULL,
                'changes' => '{"title":"Level 2","updated_at":"2021-02-01T22:27:39.000000Z","created_at":"2021-02-01T22:27:39.000000Z","id":7}',
            ),
            69 => 
            array (
                'id' => 148,
                'batch_id' => '92a162e8-97ab-4baf-9751-7961a3d0fe7c',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 7,
                'target_type' => 'App\\Course',
                'target_id' => 2,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:27:48',
                'updated_at' => '2021-02-01 22:27:48',
                'original' => NULL,
                'changes' => '{"level_id":"7","course_id":"2"}',
            ),
            70 => 
            array (
                'id' => 149,
                'batch_id' => '92a163aa-7a6a-4613-92f0-695b83f95044',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 2,
                'target_type' => 'App\\Subject',
                'target_id' => 2,
                'model_type' => 'App\\Subject',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:29:55',
                'updated_at' => '2021-02-01 22:29:55',
                'original' => NULL,
            'changes' => '{"title":"Tags","description":"<div>Elke tag bestaat uit een &lt; (kleiner dan teken) en een &gt; (groter dan teken). Direct achter het &lt;-teken<br>staat de naam van het teken.<br>Alle mogelijk namen kun je vinden op https:\\/\\/www.w3schools.com\\/tags\\/default.asp. Al deze tags<br>worden herkent door de browser en krijgen een standaard (simpele) opmaak. De standaard opmaak<br>van een tag kan verschillen in verschillende browsers.<br>De meeste tags gebruik je in paren, een begin tag en een eind tag. Bij de eind tag staat er een<br>\\/ (deelteken) voor de naam.<br>Wat tussen de tags staat is de inhoud van de tag en krijg de standaard opmaak van de tag. Dat kun je<br>bijvoorbeeld duidelijk zien als je de tags voor koppen gebruikt.<br>De teksten Hoofdstuk 1, Paragraaf 1 en Inleiding komen elk op een aparte regel en hebben als je ze in<br>de browser bekijkt een andere opmaak.<br>Sommige tags hebben geen eind-tag. Deze tags hebben geen inhoud, bijvoorbeeld de BR (line break)<br>en de HR (Horizontale lijn).<br>In veel voorbeelden van HTML zal je zien dat een tag die geen einde heeft wordt afgesloten met een<br>\\/ (deelteken) om aan te geven dat het element zichzelf afsluit. Dat was in xHTML een vereiste, in<br>HTML5 hoeft dat niet meer maar zie je het nog wel vaak<\\/div>","updated_at":"2021-02-01T22:29:55.000000Z","created_at":"2021-02-01T22:29:55.000000Z","id":2,"tags":[]}',
            ),
            71 => 
            array (
                'id' => 150,
                'batch_id' => '92a163aa-8697-4d78-99c8-588b839d7bf6',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 3,
                'target_type' => 'App\\Lesson',
                'target_id' => 3,
                'model_type' => 'App\\Lesson',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:29:55',
                'updated_at' => '2021-02-01 22:29:55',
                'original' => NULL,
            'changes' => '{"title":"Inleiding","description":"HTML is de taal die gebruikt wordt om webpagina\\u2019s te maken die in een browser (Internet Explorer,\\nFirefox, Chrome) bekeken kunnen worden. Je gebruikt HTML door in een document door tags aan te\\ngeven wat een stuk van het document betekent. Bijvoorbeeld kun je de titel van het document\\ntussen TITLE-tags zetten","updated_at":"2021-02-01T22:29:55.000000Z","created_at":"2021-02-01T22:29:55.000000Z","id":3}',
            ),
            72 => 
            array (
                'id' => 151,
                'batch_id' => '92a163aa-8a51-4d9d-b0a2-10fee056da32',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 2,
                'target_type' => 'App\\Module',
                'target_id' => 2,
                'model_type' => 'App\\Module',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:29:55',
                'updated_at' => '2021-02-01 22:29:55',
                'original' => NULL,
                'changes' => '{"title":"HTML & CSS","code":"A1","description":"In deze opdracht leer je HTML5 gebruiken voor het indelen en CSS3 voor het opmaken van een\\nwebpagina. Eerst leer je de twee technieken vervolgens gebruik je deze bij het maken van de\\neindopdracht.","updated_at":"2021-02-01T22:29:54.000000Z","created_at":"2021-02-01T22:29:54.000000Z","id":2}',
            ),
            73 => 
            array (
                'id' => 152,
                'batch_id' => '92a163c2-d715-429e-ac86-6c34660060bd',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 5,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:30:11',
                'updated_at' => '2021-02-01 22:30:11',
                'original' => NULL,
                'changes' => '{"module_id":"2","level_id":"5"}',
            ),
            74 => 
            array (
                'id' => 153,
                'batch_id' => '92a163de-5f2a-4f32-b7db-9ca052dba243',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 1,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:30:29',
                'updated_at' => '2021-02-01 22:30:29',
                'original' => NULL,
                'changes' => '{"module_id":"2","level_id":"1"}',
            ),
            75 => 
            array (
                'id' => 154,
                'batch_id' => '92a163ee-020d-4d87-a381-f88e00521fdf',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 2,
                'target_type' => 'App\\Level',
                'target_id' => 5,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:30:39',
                'updated_at' => '2021-02-01 22:30:39',
                'original' => NULL,
                'changes' => NULL,
            ),
            76 => 
            array (
                'id' => 155,
                'batch_id' => '92a16470-6041-4c0a-870f-033275ff6d81',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 1,
                'target_type' => 'App\\Course',
                'target_id' => 2,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:32:04',
                'updated_at' => '2021-02-01 22:32:04',
                'original' => NULL,
                'changes' => NULL,
            ),
            77 => 
            array (
                'id' => 156,
                'batch_id' => '92a1655f-4d8a-4cc5-b3d4-5fc527b383ae',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 1,
                'target_type' => 'App\\Subject',
                'target_id' => 1,
                'model_type' => 'App\\Subject',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:34:41',
                'updated_at' => '2021-02-01 22:34:41',
                'original' => '{"description":"In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden."}',
                'changes' => '{"description":"<div>In dit blok gaan we het hebben over wat variabelen zijn en waar ze voor gebruikt worden.<\\/div>"}',
            ),
            78 => 
            array (
                'id' => 157,
                'batch_id' => '92a1655f-5ad6-4b6c-9545-3ebba4198a5f',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Lesson',
                'actionable_id' => 1,
                'target_type' => 'App\\Lesson',
                'target_id' => 1,
                'model_type' => 'App\\Lesson',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:34:41',
                'updated_at' => '2021-02-01 22:34:41',
                'original' => '[]',
                'changes' => '[]',
            ),
            79 => 
            array (
                'id' => 158,
                'batch_id' => '92a1655f-63b4-4aa4-bf3d-0888c9b03a26',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Subject',
                'actionable_id' => 2,
                'target_type' => 'App\\Subject',
                'target_id' => 2,
                'model_type' => 'App\\Subject',
                'model_id' => 2,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:34:41',
                'updated_at' => '2021-02-01 22:34:41',
            'original' => '{"title":"Tags","description":"<div>Elke tag bestaat uit een &lt; (kleiner dan teken) en een &gt; (groter dan teken). Direct achter het &lt;-teken<br>staat de naam van het teken.<br>Alle mogelijk namen kun je vinden op https:\\/\\/www.w3schools.com\\/tags\\/default.asp. Al deze tags<br>worden herkent door de browser en krijgen een standaard (simpele) opmaak. De standaard opmaak<br>van een tag kan verschillen in verschillende browsers.<br>De meeste tags gebruik je in paren, een begin tag en een eind tag. Bij de eind tag staat er een<br>\\/ (deelteken) voor de naam.<br>Wat tussen de tags staat is de inhoud van de tag en krijg de standaard opmaak van de tag. Dat kun je<br>bijvoorbeeld duidelijk zien als je de tags voor koppen gebruikt.<br>De teksten Hoofdstuk 1, Paragraaf 1 en Inleiding komen elk op een aparte regel en hebben als je ze in<br>de browser bekijkt een andere opmaak.<br>Sommige tags hebben geen eind-tag. Deze tags hebben geen inhoud, bijvoorbeeld de BR (line break)<br>en de HR (Horizontale lijn).<br>In veel voorbeelden van HTML zal je zien dat een tag die geen einde heeft wordt afgesloten met een<br>\\/ (deelteken) om aan te geven dat het element zichzelf afsluit. Dat was in xHTML een vereiste, in<br>HTML5 hoeft dat niet meer maar zie je het nog wel vaak<\\/div>"}',
                'changes' => '{"title":"Studieblok 2: Loops in Javascript","description":"Je gaat in deze les leren op welke verschillende manieren loops gebruikt kunnen worden."}',
            ),
            80 => 
            array (
                'id' => 159,
                'batch_id' => '92a1655f-6a87-4c73-abad-8acd01516e92',
                'user_id' => 4,
                'name' => 'Update',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 1,
                'target_type' => 'App\\Module',
                'target_id' => 1,
                'model_type' => 'App\\Module',
                'model_id' => 1,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:34:41',
                'updated_at' => '2021-02-01 22:34:41',
                'original' => '{"title":"Javscript"}',
                'changes' => '{"title":"Javascript"}',
            ),
            81 => 
            array (
                'id' => 163,
                'batch_id' => '92a1666e-bf9c-49bc-8014-3f02ba6d7622',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 14,
                'target_type' => 'App\\Competence',
                'target_id' => 14,
                'model_type' => 'App\\Competence',
                'model_id' => 14,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:37:39',
                'updated_at' => '2021-02-01 22:37:39',
                'original' => NULL,
                'changes' => '{"description":"Kan het verloop van een algoritme beschrijven, bijvoorbeeld aan de hand van een PSD. B1-k2-w3","updated_at":"2021-02-01T22:37:39.000000Z","created_at":"2021-02-01T22:37:39.000000Z","id":14}',
            ),
            82 => 
            array (
                'id' => 164,
                'batch_id' => '92a1666e-ccf2-44ff-8634-abfc543db108',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Competence',
                'actionable_id' => 15,
                'target_type' => 'App\\Competence',
                'target_id' => 15,
                'model_type' => 'App\\Competence',
                'model_id' => 15,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:37:39',
                'updated_at' => '2021-02-01 22:37:39',
                'original' => NULL,
            'changes' => '{"description":"Kan eenvoudige voorwaardelijke code (if\\/switch) en herhaalde code (for\\/while) toepassen bij het realiseren van een eenvoudige applicatie. b1-k2-w1","updated_at":"2021-02-01T22:37:39.000000Z","created_at":"2021-02-01T22:37:39.000000Z","id":15}',
            ),
            83 => 
            array (
                'id' => 165,
                'batch_id' => '92a1666e-d07f-4b07-b006-c8ed5c9f3dbf',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 8,
                'target_type' => 'App\\Level',
                'target_id' => 8,
                'model_type' => 'App\\Level',
                'model_id' => 8,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:37:39',
                'updated_at' => '2021-02-01 22:37:39',
                'original' => NULL,
                'changes' => '{"title":"Level 1","updated_at":"2021-02-01T22:37:39.000000Z","created_at":"2021-02-01T22:37:39.000000Z","id":8}',
            ),
            84 => 
            array (
                'id' => 166,
                'batch_id' => '92a1667d-4c37-4bda-ac6f-ef3933b59c14',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Level',
                'actionable_id' => 8,
                'target_type' => 'App\\Course',
                'target_id' => 2,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:37:48',
                'updated_at' => '2021-02-01 22:37:48',
                'original' => NULL,
                'changes' => '{"level_id":"8","course_id":"2"}',
            ),
            85 => 
            array (
                'id' => 167,
                'batch_id' => '92a166c9-b3f5-4196-b963-1b0101248cdd',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Module',
                'target_id' => 3,
                'model_type' => 'App\\Module',
                'model_id' => 3,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:38:38',
                'updated_at' => '2021-02-01 22:38:38',
                'original' => NULL,
                'changes' => '{"title":"Basisprogrammeren PHP","code":"A1","description":"De beginselen van programmeren in PHP.","updated_at":"2021-02-01T22:38:38.000000Z","created_at":"2021-02-01T22:38:38.000000Z","id":3}',
            ),
            86 => 
            array (
                'id' => 168,
                'batch_id' => '92a166e5-cb34-49c9-9dd5-e3df66095fab',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 5,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:38:57',
                'updated_at' => '2021-02-01 22:38:57',
                'original' => NULL,
                'changes' => '{"module_id":"3","level_id":"5"}',
            ),
            87 => 
            array (
                'id' => 169,
                'batch_id' => '92a166ff-9503-4c38-9f44-84642d8028a0',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 1,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:39:14',
                'updated_at' => '2021-02-01 22:39:14',
                'original' => NULL,
                'changes' => '{"module_id":"3","level_id":"1"}',
            ),
            88 => 
            array (
                'id' => 170,
                'batch_id' => '92a16708-216d-4fca-9f34-4d4d845d411d',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 1,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:39:19',
                'updated_at' => '2021-02-01 22:39:19',
                'original' => NULL,
                'changes' => NULL,
            ),
            89 => 
            array (
                'id' => 171,
                'batch_id' => '92a16717-ec2d-4d8c-b636-8b050624ea57',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 5,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:39:30',
                'updated_at' => '2021-02-01 22:39:30',
                'original' => NULL,
                'changes' => NULL,
            ),
            90 => 
            array (
                'id' => 172,
                'batch_id' => '92a1671d-a128-40ac-bae0-a99c33dc8152',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 1,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:39:33',
                'updated_at' => '2021-02-01 22:39:33',
                'original' => NULL,
                'changes' => '{"module_id":"3","level_id":"1"}',
            ),
            91 => 
            array (
                'id' => 173,
                'batch_id' => '92a1672b-0acf-44e2-930b-8132b8e9c449',
                'user_id' => 4,
                'name' => 'Detach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 1,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:39:42',
                'updated_at' => '2021-02-01 22:39:42',
                'original' => NULL,
                'changes' => NULL,
            ),
            92 => 
            array (
                'id' => 174,
                'batch_id' => '92a16731-1753-4bcb-9c4b-f0242839e482',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 3,
                'target_type' => 'App\\Level',
                'target_id' => 8,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:39:46',
                'updated_at' => '2021-02-01 22:39:46',
                'original' => NULL,
                'changes' => '{"module_id":"3","level_id":"8"}',
            ),
            93 => 
            array (
                'id' => 175,
                'batch_id' => '92a168be-4f4a-41ff-8d64-ab8412cba14c',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 4,
                'target_type' => 'App\\Module',
                'target_id' => 4,
                'model_type' => 'App\\Module',
                'model_id' => 4,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:44:06',
                'updated_at' => '2021-02-01 22:44:06',
                'original' => NULL,
                'changes' => '{"title":"Code indelen in PHP","code":"A2","description":"Code opdelen in php.","updated_at":"2021-02-01T22:44:06.000000Z","created_at":"2021-02-01T22:44:06.000000Z","id":4}',
            ),
            94 => 
            array (
                'id' => 176,
                'batch_id' => '92a168cd-c1fb-4140-a6f8-9ad9de349a02',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 4,
                'target_type' => 'App\\Level',
                'target_id' => 7,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:44:17',
                'updated_at' => '2021-02-01 22:44:17',
                'original' => NULL,
                'changes' => '{"module_id":"4","level_id":"7"}',
            ),
            95 => 
            array (
                'id' => 177,
                'batch_id' => '92a16907-8a66-4c2b-a300-49c6092abde1',
                'user_id' => 4,
                'name' => 'Create',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 5,
                'target_type' => 'App\\Module',
                'target_id' => 5,
                'model_type' => 'App\\Module',
                'model_id' => 5,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:44:54',
                'updated_at' => '2021-02-01 22:44:54',
                'original' => NULL,
                'changes' => '{"title":"Introductie programmeren in JAVA","code":"A1","description":"Programmeren in Java","updated_at":"2021-02-01T22:44:54.000000Z","created_at":"2021-02-01T22:44:54.000000Z","id":5}',
            ),
            96 => 
            array (
                'id' => 178,
                'batch_id' => '92a16913-eb01-40e7-9c34-2a0bdd36e09e',
                'user_id' => 4,
                'name' => 'Attach',
                'actionable_type' => 'App\\Module',
                'actionable_id' => 5,
                'target_type' => 'App\\Level',
                'target_id' => 8,
                'model_type' => 'Illuminate\\Database\\Eloquent\\Relations\\Pivot',
                'model_id' => NULL,
                'fields' => '',
                'status' => 'finished',
                'exception' => '',
                'created_at' => '2021-02-01 22:45:03',
                'updated_at' => '2021-02-01 22:45:03',
                'original' => NULL,
                'changes' => '{"module_id":"5","level_id":"8"}',
            ),
        ));
        
        
    }
}